modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/team-abnormals/neapolitan/issues"
license = "https://github.com/team-abnormals/neapolitan/blob/main/LICENSE.txt"

[[mods]]
    modId = "neapolitan"
    version = "${file.jarVersion}"
    logoFile = "logo.png"
    authors = "Team Abnormals"
    credits = "bageldotjpg, five"
    displayName = "Neapolitan"
    description = '''
    Adds new flavors and fruits to create tasty Ice Creams, Milkshakes, Cakes, and more!
    '''

[[dependencies.neapolitan]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.16.3,1.17)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.neapolitan]]
    modId = "forge"
    mandatory = true
    versionRange = "[34.1.42,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.neapolitan]]
    modId = "abnormals_core"
    mandatory = true
    versionRange = "[3.0.4,)"
    ordering = "AFTER"
    side = "BOTH"
