modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/team-abnormals/neapolitan/issues"
license = "https://github.com/team-abnormals/neapolitan/blob/main/LICENSE.txt"

[[mods]]
    modId = "neapolitan"
    version = "${file.jarVersion}"
    logoFile = "logo.png"
    itemIcon = "neapolitan:neapolitan_ice_cream"
    configBackground = "neapolitan:textures/block/chocolate_bricks.png"
    authors = "Team Abnormals"
    credits = "bageldotjpg, five, Markus1002"
    displayURL = "https://www.teamabnormals.com/mods/neapolitan"
    displayName = "Neapolitan"
    description = '''
    Adds new flavors and fruits to create tasty Ice Creams, Milkshakes, Cakes, and more!
    '''

[[dependencies.neapolitan]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19,1.20)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.neapolitan]]
    modId = "forge"
    mandatory = true
    versionRange = "[41.1.0,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.neapolitan]]
    modId = "blueprint"
    mandatory = true
    versionRange = "[6.0.5,)"
    ordering = "AFTER"
    side = "BOTH"